version: '3.1'

services:
  db:
    image: postgres:16.1-alpine3.18
    container_name: fiado_rs_postgres
    restart: always
    ports:
      - 54355:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_USER: ${DB_USERNAME} 
      POSTGRES_DB: ${DB_NAME} 
    networks:
      - fiado

networks:
  fiado:
    external:
      true